### ISSUE TITLE
NullPointerException when @XMFPackage is missing

### ISSUE THREAD

**Issue by vsimko** [d3sreq/xmf#9]
``` Xtend
package org.xmf.experiment.variations
import org.xmf.annot.XMF
@XMF class A {}
```

```
Description Resource    Path    Location    Type
Error during annotation processing:
java.lang.NullPointerException
    at org.xmf.utils.AnnotUtils.getModelPackageName(AnnotUtils.java:98)
    at org.xmf.annot.ModelFactoryTransformation.<init>(ModelFactoryTransformation.java:59)
    at org.xmf.annot.XmfCompilationParticipant$2.apply(XmfCompilationParticipant.java:50)
    at org.xmf.annot.XmfCompilationParticipant$2.apply(XmfCompilationParticipant.java:1)
    at org.eclipse.xtext.xbase.lib.MapExtensions.forEach(MapExtensions.java:41)
    at org.xmf.annot.XmfCompilationParticipant.doTransform(XmfCompilationParticipant.java:59)
    Pokus.xtend /TestXtendModel/src/org/xmf/experiment/variations   line: 3 /TestXtendModel/src/org/xmf/experiment/variations/Pokus.xtend   Xtend Problem
```

**Comment by vsimko** [comment]
Forgot to mention that the following works fine:

``` Xtend
@XMFPackage("hello")
@XMF class A {}
```
